### ISSUE TITLE
How to relate the label name with the index?

### ISSUE THREAD

**Issue by lannester666** [CurryTang/TSGFM#2]
Thanks for your great work! I have a question about the dataset's category names. I notice that for each dataset there is a 'categories.csv' file showing the category names, and for some datasets like cora, citeseer, the loaded data has an attribute 'label_names', which reflects with the label index. However I find this sequence is not totally correspond to the category in 'categories.csv'.  For example, for cora, the label 0 corresponds to the first item in 'label_names', which is "Rule_Learning". but in 'categories.csv', the first label name is "Theory". So for the datasets like 'dblp' which don't have the 'label_names' attribute, how can I get each label's category name?

**Comment by CurryTang** [comment]
Hi, we use the `label_names` of the `geometric_data_processed.pt` file as the label names

**Comment by lannester666** [comment]
Maybe it's a coincidence, but **DBLP** dataset doesn't have **label_names** attribute:(
<img width="795" alt="截屏2024-09-14 10 56 51" src="https://github.com/user-attachments/assets/4c060355-cb02-44c8-85fc-f7fac857ac34">

**Comment by CurryTang** [comment]
You may use `class_node_text_feat` in this case

**Comment by lannester666** [comment]
I'm still confused. Is there any way for me to get the original node feature texts and label names? Or I can only get the embedding in this case?

**Comment by CurryTang** [comment]
Sorry for the late reply. For the original class description, I think you may use the `categories.csv` file ( cora, pubmed may be an exception since I may take the original file from OneForAll's repo). For the original text, it's not directly accessible from the pyg object. You may copy the process code from `gen_data.py`. I will update these things when preparing the camera ready version.

**Comment by lannester666** [comment]
Thank you for your answer!
